name: First-Deploy
env:
  VAR1 : "Это аргумент 1"
  VAR2 : "Это аргумент 2"
on:
  push:
    branches: 
      - main
jobs: 
  my_test1:
    runs-on: ubuntu-latest

    steps:
    - name: Run script
      run: echo Hello, script
  my_var1:
    runs-on: ubuntu-latest
    steps:
    - name: My Var
      run: echo $VAR1


  my_var2:
    runs-on: ubuntu-latest
    steps:
    - name: My Var
      run: echo $VAR2

  my_test2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run test2
      run: echo Hello it test 2.
    
