name: First-Deploy-Docker


on:
  push:
    branches:
      - main

jobs:
  Build_image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Image
      run: docker build -t deployapp:1 .
    - name: Run Docker
      run: docker run -d --rm --name web -p 80:8080 deployapp:1
    - name: Check 
      run: docker ps
